[package]
name = "rustyrtc"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
eframe = { version = "0.28", features = ["wgpu"] }
egui = "0.28"
openh264 = "0.9"
opencv = "0.97"
bytemuck = "1.24.0"
wgpu = "27.0.1"

[features]
default = []
test-support = []


[lints.clippy]
all         = { level = "deny", priority = -1 }
pedantic    = { level = "deny", priority = -1 }
nursery     = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
