[package]
name = "rustyrtc"
version = "0.1.0"
edition = "2024"

[dependencies]

[features]
default = []
test-support = []


[lints.clippy]
all         = { level = "deny", priority = -1 }
pedantic    = { level = "deny", priority = -1 }
nursery     = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
